-- Create a table for public profiles using the user's ID
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  role text check (role in ('investor', 'entrepreneur', 'admin', 'staff')),
  status text default 'Active',
  type text default 'Ordinary', -- For investors: Certified/Ordinary
  business_name text, -- For entrepreneurs
  phone text,
  region text, -- For staff
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for projects
create table projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text,
  entrepreneur_id uuid references profiles(id),
  goal numeric,
  funding_raised numeric default 0,
  status text default 'Pending' check (status in ('Pending', 'Active', 'Funded', 'Rejected')),
  trust_score integer default 0
);

alter table projects enable row level security;

create policy "Projects are viewable by everyone."
  on projects for select
  using ( true );

create policy "Entrepreneurs can insert their own projects."
  on projects for insert
  with check ( auth.uid() = entrepreneur_id );
  
-- Create a trigger to create a profile entry when a new user signs up
-- function
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, role, status, business_name, phone)
  values (
    new.id, 
    new.email, 
    new.raw_user_meta_data->>'full_name', 
    coalesce(new.raw_user_meta_data->>'role', 'investor'),
    'Active',
    new.raw_user_meta_data->>'business_name',
    new.raw_user_meta_data->>'phone'
  );
  return new;
end;
$$ language plpgsql security definer;

-- trigger
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
