 -- Create a table to track field agent verifications by staff
drop table if exists agent_verifications cascade;
create table if not exists agent_verifications (
  id bigint generated by default as identity primary key,
  agent_id uuid references public.profiles(id) on delete cascade not null,
  verifier_id uuid references public.profiles(id) on delete set null,
  comment text not null,
  proof_image_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies (optional but good practice)
alter table agent_verifications enable row level security;

create policy "Staff can view verifications"
  on agent_verifications for select
  using (exists (select 1 from profiles where id = auth.uid() and role in ('staff', 'admin')));

create policy "Staff can insert verifications"
  on agent_verifications for insert
  with check (exists (select 1 from profiles where id = auth.uid() and role in ('staff', 'admin')));
